--增加字段
ALTER TABLE CLAIMOWNER.CL_TASK ADD VEH_CONTACTOR VARCHAR2(50);
ALTER TABLE CLAIMOWNER.CL_TASK ADD MOBILE VARCHAR2(50);

COMMENT ON COLUMN CLAIMOWNER.CL_TASK.VEH_CONTACTOR IS '车辆联系人';
COMMENT ON COLUMN CLAIMOWNER.CL_TASK.MOBILE IS '联系电话';