CREATE TABLE RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC
(
  ID           NUMBER(18),
  DEALER_CODE  VARCHAR2(32),
  IP_ADDRESS   VARCHAR2(32),
  PLATE_NO     VARCHAR2(32),
  ENTER_DATE   DATE,
  CONTENT1     VARCHAR2(4000),
  CONTENT2     VARCHAR2(4000),
  CONTENT3     VARCHAR2(4000),
  CONTENT4     VARCHAR2(4000),
  CREATE_TIME  DATE,
  CREATE_USER  VARCHAR2(32),
  UPDATE_TIME  DATE,
  UPDATE_USER  VARCHAR2(32)
) tablespace TBS_DATA_RENEW;

COMMENT ON TABLE RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC IS '车辆进店日志';
COMMENT ON COLUMN RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC.ID IS 'ID';
COMMENT ON COLUMN RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC.DEALER_CODE IS '经销商代码';
COMMENT ON COLUMN RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC.IP_ADDRESS IS '摄像头IP';
COMMENT ON COLUMN RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC.PLATE_NO IS '车牌号';
COMMENT ON COLUMN RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC.ENTER_DATE IS '进店时间';
COMMENT ON COLUMN RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC.CONTENT1 IS '内容1';
COMMENT ON COLUMN RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC.CONTENT2 IS '内容2';
COMMENT ON COLUMN RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC.CONTENT3 IS '内容3';
COMMENT ON COLUMN RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC.CONTENT4 IS '内容4';
COMMENT ON COLUMN RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC.CREATE_USER IS '创建用户';
COMMENT ON COLUMN RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC.UPDATE_USER IS '更新用户';

CREATE INDEX RENEWOWNER.IDX_ENTER_LOG_ARC_TIME ON RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC (ENTER_DATE) TABLESPACE TBS_INDEX_RENEW;
CREATE UNIQUE INDEX RENEWOWNER.IDX_VEHICLE_ENTER_LOG_ARC_ID ON RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC(ID) TABLESPACE TBS_INDEX_RENEW;
CREATE INDEX RENEWOWNER.IDX_ENTER_LOG_ARC_PLATENO ON RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC(PLATE_NO) TABLESPACE TBS_INDEX_RENEW;

CREATE OR REPLACE SYNONYM RENEWAPP.RS_VEHICLE_ENTER_LOG_ARC FOR RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC;
CREATE OR REPLACE SYNONYM RENEWDEV.RS_VEHICLE_ENTER_LOG_ARC FOR RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC;

ALTER TABLE RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC ADD CONSTRAINT PK_VEHICLE_ENTER_LOG_ARC PRIMARY KEY(ID) USING INDEX RENEWOWNER.IDX_VEHICLE_ENTER_LOG_ARC_ID ;

GRANT DELETE, INSERT, SELECT, UPDATE ON RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC TO RENEWDEV;
GRANT DELETE, INSERT, SELECT, UPDATE ON RENEWOWNER.RS_VEHICLE_ENTER_LOG_ARC TO RENEWAPP;
