ALTER TABLE RENEWOWNER.RS_RENEW_TASK_ARC ADD (end_date_md varchar2(6));

COMMENT ON COLUMN RENEWOWNER.RS_RENEW_TASK_ARC.end_date_md IS '保险到期日(MM-dd)';

CREATE INDEX RENEWOWNER.IDX_RS_RENEW_TASK_ARC_MD  ON RENEWOWNER.RS_RENEW_TASK_ARC (END_DATE_MD) tablespace TBS_INDEX_RENEW;